# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('_type', models.IntegerField(verbose_name='身份')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='问卷名')),
                ('num', models.IntegerField(default=0, verbose_name='参与人数')),
                ('url', models.CharField(max_length=64, verbose_name='学生填写问卷地址')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='问题')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='班级名')),
                ('student_num', models.IntegerField(verbose_name='学生数')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='问题类型')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='选项')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
        ),
        migrations.CreateModel(
            name='Type_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app01.Person')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
            ],
            bases=('app01.person',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app01.Person')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
            ],
            bases=('app01.person',),
        ),
        migrations.AddField(
            model_name='type',
            name='type_choice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_type', to='app01.Type_Choice'),
        ),
        migrations.AddField(
            model_name='type',
            name='type_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_type', to='app01.Type_Score'),
        ),
        migrations.AddField(
            model_name='type',
            name='type_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_type', to='app01.Type_Text'),
        ),
        migrations.AddField(
            model_name='questions',
            name='_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='type_question', to='app01.Type'),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_question', to='app01.QuestionPapers'),
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='QuestionPapers_class', to='app01.Student_Class', verbose_name='关联班级'),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='app01.Type_Choice', verbose_name='单选'),
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_content', to='app01.Type_Text', verbose_name='评价'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_question', to='app01.Questions', verbose_name='关联试题'),
        ),
        migrations.AddField(
            model_name='student_class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Teacher', verbose_name='班主任'),
        ),
        migrations.AddField(
            model_name='student',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Student_Class', verbose_name='对应班级'),
        ),
        migrations.AddField(
            model_name='questionpapers',
            name='student',
            field=models.ManyToManyField(related_name='QuestionPapers_student', to='app01.Student', verbose_name='关联学生'),
        ),
        migrations.AddField(
            model_name='answer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_student', to='app01.Student', verbose_name='关联学生'),
        ),
    ]
