# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpapers',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='QuestionPapers_student', to='app01.Student', verbose_name='关联学生'),
        ),
    ]
