# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171205_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpapers',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='questions',
            field=models.ManyToManyField(related_name='QuestionPapers_student', to='app01.QuestionPapers', verbose_name='关联问卷'),
        ),
    ]
