# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20171205_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='type_choice',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_score',
        ),
        migrations.RemoveField(
            model_name='type',
            name='type_text',
        ),
        migrations.AddField(
            model_name='type_choice',
            name='type_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choice_type', to='app01.Type'),
        ),
        migrations.AddField(
            model_name='type_score',
            name='type_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_type', to='app01.Type'),
        ),
        migrations.AddField(
            model_name='type_text',
            name='type_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_type', to='app01.Type'),
        ),
    ]
