# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171205_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_question', to='app01.Type'),
        ),
    ]
