# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171205_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionpapers',
            old_name='_class',
            new_name='student_class',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='_type',
            new_name='question_type',
        ),
    ]
